export './experiment/HasHeight.dart';

// dynamics
export './experiment/dynamics/buildingBlocksStability.dart';
export './experiment/dynamics/buoyancyAndActionReaction.dart';
export './experiment/dynamics/buoyancyComparison.dart';
export './experiment/dynamics/elasticCollision1D.dart';
export './experiment/dynamics/elasticCollision2D.dart';
export './experiment/dynamics/fook.dart';
export './experiment/dynamics/freeFall.dart';
export './experiment/dynamics/jupiter.dart';
export './experiment/dynamics/kineticFriction.dart';
export './experiment/dynamics/moonOrbit.dart';
export './experiment/dynamics/oneSideLift.dart';
export './experiment/dynamics/pendulumPeriodMeasurement.dart';
export './experiment/dynamics/planets.dart';
export './experiment/dynamics/staticFriction.dart';
export './experiment/dynamics/verticalSpringOscillation.dart';
export './experiment/dynamics/barometer.dart';
export './experiment/dynamics/accelerometer.dart';
export './experiment/dynamics/AccelerometerExperimentWidget.dart';
export './experiment/dynamics/BarometerExperimentWidget.dart';
export './experiment/dynamics/centripetalForceDisappears.dart';


// electroMagnetism
export './experiment/electroMagnetism/ampereLawTorque.dart';
export './experiment/electroMagnetism/bismuthDiamagnetism.dart';
export './experiment/electroMagnetism/capacitanceParallelCombination.dart';
export './experiment/electroMagnetism/capacitanceSeriesCombination.dart';
export './experiment/electroMagnetism/capacitorChargeStorage.dart';
export './experiment/electroMagnetism/capacitorIntroduction.dart';
export './experiment/electroMagnetism/coilProperties.dart';
export './experiment/electroMagnetism/diodeIntroduction.dart';
export './experiment/electroMagnetism/forceBetweenParallelCurrents.dart';
export './experiment/electroMagnetism/lemonBatteryVoltage.dart';
export './experiment/electroMagnetism/lorentzForce.dart';
export './experiment/electroMagnetism/magneticFieldCircularLoop.dart';
export './experiment/electroMagnetism/solenoidMagneticField.dart';
export './experiment/electroMagnetism/neodymiumMagnetFieldMeasurement.dart';
export './experiment/electroMagnetism/parallelPlateCapacitanceMeasurement.dart';
export './experiment/electroMagnetism/parallelResistance.dart';
export './experiment/electroMagnetism/rcCircuit.dart';
export './experiment/electroMagnetism/resistanceMeasurement.dart';
export './experiment/electroMagnetism/resistanceVsLength.dart';
export './experiment/electroMagnetism/resistivityTemperatureDependence.dart';
export './experiment/electroMagnetism/seriesResistance.dart';
export './experiment/electroMagnetism/solenoidSelfInductance.dart';
export './experiment/electroMagnetism/ohmsLaw.dart';
export './experiment/electroMagnetism/magnetometer.dart';
export './experiment/electroMagnetism/magnetometer.dart';
export './experiment/electroMagnetism/MagnetometerExperimentWidget.dart';


// thermoDynamics
export './experiment/thermoDynamics/boyle_law.dart';

// waves
export './experiment/waves/closedPipeResonance.dart';
export './experiment/waves/diffractionGrating.dart';
export './experiment/waves/openPipeResonance.swift.dart';
export './experiment/waves/spectroscopy.dart';
export './experiment/waves/beat.dart';
export './experiment/waves/doppler.dart';
export './experiment/waves/dopplerObserverMoving.dart';
export './experiment/waves/luxMeasurement.dart';
export './experiment/waves/LuxMeasurementWidget.dart';
export './experiment/waves/FrequencyMeasureWidget.dart';
export './experiment/waves/ToneGeneratorWidget.dart';
export './experiment/waves/frequencyAndDoReMi.dart';
export './experiment/waves/PianoWidget.dart';
export './experiment/waves/soundGenerate.dart';

export './theory/mathematics/sequences_infinite_geometric_series_coefficient_of_restitution.dart';
export './theory/mathematics/sequences_harmonic_sequence.dart';
export './theory/mathematics/sequences_trig_arithmetic_inside.dart';

export './theory/mathematics/differentiation_product_rule.dart';
export './theory/mathematics/differentiation_position_velocity_acceleration.dart';
export './theory/mathematics/differentiation_chain_rule.dart';
export './theory/mathematics/differentiation_maclaurin_approximation.dart';

export './theory/mathematics/integration_displacement_velocity_variation.dart';
export './theory/mathematics/integration_fprime_over_f.dart';
export './theory/mathematics/integration_trig_rms_average_zero.dart';
export './theory/mathematics/integration_graph_average_value.dart';
export './theory/mathematics/integration_reciprocal_isothermal.dart';
export './theory/mathematics/integration_polynomial_adiabatic.dart';
export './theory/mathematics/integration_tan_substitution_circular_current_solenoid.dart';
export './theory/mathematics/integration_substitution_kx_squared.dart';
export './theory/mathematics/integration_mean_value_theorem.dart';
export './theory/mathematics/integration_riemann_sum.dart';
export './theory/mathematics/integration_fundamental_theorem_calculus.dart';

export './theory/mathematics/vectorComponent.dart';
export './theory/mathematics/vectors_basic.dart';
export './theory/mathematics/vectors_addition.dart';
export './theory/mathematics/vectors_subtraction_relative_velocity_position.dart';
export './theory/mathematics/vectors_norm.dart';
export './theory/mathematics/vectors_decomposition.dart';
export './theory/mathematics/vectors_components.dart';
export './theory/mathematics/vectors_linear_independence.dart';
export './theory/mathematics/vectors_centroid_internal_division.dart';
export './theory/mathematics/vectors_cross_product.dart';
export './theory/mathematics/vectors_dot_product.dart';
export './theory/mathematics/vectors_coordinate_transformation.dart';
export './theory/mathematics/vectors_vector_fields.dart';

export './theory/mathematics/trig_sum_to_product.dart';
export './theory/mathematics/trig_functions_basic.dart';
export './theory/mathematics/trig_periodicity.dart';
export './theory/mathematics/trig_sum_to_product_separation.dart';
export './theory/mathematics/trig_addition_45deg.dart';

export './theory/mathematics/funceq_recurrence_initial_value.dart';
export './theory/mathematics/funceq_functional_equations.dart';
export './theory/mathematics/funceq_free_fall.dart';
export './theory/mathematics/funceq_binet_equation.dart';
export './theory/mathematics/funceq_simple_harmonic_motion.dart';
export './theory/mathematics/funceq_air_resistance.dart';
export './theory/mathematics/funceq_damped_oscillation.dart';
export './theory/mathematics/funceq_homogeneous_differential_equations.dart';
export './theory/mathematics/funceq_nonhomogeneous_differential_equations.dart';
export './theory/mathematics/funceq_systems_circuits_lorentz.dart';
export './theory/mathematics/funceq_poisson_equation.dart';
export './theory/mathematics/funceq_uniqueness_of_solutions.dart';

export './theory/mathematics/conic_2d_waves_hyperbola_equation.dart';
export './theory/mathematics/conic_quadratic_vertex_ellipse.dart';
export './theory/mathematics/conic_ellipse_area.dart';
export './theory/mathematics/conic_ellipse_equation.dart';
export './theory/mathematics/conic_ellipse_parametrization.dart';
export './theory/mathematics/conic_circle_parabola_approximation.dart';
export './theory/mathematics/conic_foci.dart';
export './theory/mathematics/conic_eccentricity.dart';
export './theory/mathematics/conic_polar_equations.dart';

export './theory/mathematics/existence_for_all_t_fx_t_equals_zero_node.dart';
export './theory/mathematics/existence_for_all_t_fprime_fx_t_equals_zero_antinode.dart';
export './theory/mathematics/existence_exists_n_sin_theta_equals_na.dart';

export './theory/mathematics/multivar_trig_1_plus_1_vars.dart';
export './theory/mathematics/multivar_trig_2_plus_1_vars.dart';
export './theory/mathematics/multivar_trig_3_plus_1_vars.dart';

export './theory/mathematics/others_systems_linear_equations.dart';
export './theory/mathematics/others_harmonic_mean.dart';
export './theory/mathematics/others_line_point_symmetry_transformations.dart';
export './theory/mathematics/others_spiral.dart';
export './theory/mathematics/others_line_integrals.dart';
export './theory/mathematics/others_surface_integrals_flux.dart';
export './theory/mathematics/others_envelope_curves.dart';
export './theory/mathematics/others_rms_velocity.dart';
export './theory/mathematics/others_dimensional_analysis.dart';
export './theory/mathematics/others_elliptic_integrals_circular_current_pendulum.dart';


// theory/dynamics
export './theory/dynamics/uniformAcceleration.dart';
export './theory/dynamics/eqOfMotion.dart';
export './theory/dynamics/momentum.dart';
export './theory/dynamics/workAndEnergy.dart';
export './theory/dynamics/kepler-first-law.dart';
export './theory/dynamics/kepler-second-law.dart';
export './theory/dynamics/kepler-third-law.dart';
export './theory/dynamics/universal-gravitation-energy-conserv.dart';
export './theory/dynamics/conservativeForce.dart';
export './theory/dynamics/simplePendulum.dart';
export './theory/dynamics/inertialForceParallel.dart';
export './theory/dynamics/inertialForceRotation.dart';
export './theory/dynamics/doubleMassPoint.dart';
export './theory/dynamics/collisionConservation.dart';
export './theory/dynamics/doubleMassPointEnergy.dart';
export './theory/dynamics/angularMomentumAndTorque.dart';
export './theory/dynamics/systemsOfParticles.dart';
export './theory/dynamics/conicalPendulum.dart';
export './theory/dynamics/nonUniformCircularMotion.dart';
export './theory/dynamics/uniformCircularMotion.dart';
export './theory/dynamics/simpleHarmonicMotionSolution.dart';
export './theory/dynamics/fookEnergyConservation.dart';
export './theory/dynamics/surfaceGravityEnergyConservation.dart';
export './theory/dynamics/surfaceGravAndFookEnergyConservation.dart';
export './theory/dynamics/twoDimPolarCoordinatesEqOfMotion.dart';
export './theory/dynamics/rigidBodyBalanceOfForces.dart';
export './theory/dynamics/workAndLineIntegral.dart';
export './theory/dynamics/runge_lenz_vector.dart';
export './theory/dynamics/1d_elastic_collision_energy_conservation.dart';
export './theory/dynamics/simple_pendulum_period_elliptic_integrals.dart';
export './theory/dynamics/moment_of_inertia.dart';
export './theory/dynamics/physical_pendulum.dart';
export './theory/dynamics/particle_motion_gravity_with_air_resistance.dart';
export './theory/dynamics/2d_elastic_collision_equal_mass_on_stationary.dart';

// theory/electroMagnetism
export './theory/electroMagnetism/electoricGaussLaw.dart';
export './theory/electroMagnetism/ampereLaw.dart';
export './theory/electroMagnetism/lorentzForceAndCircleMove.dart';
export './theory/electroMagnetism/infiniteStraightCurrent.dart';
export './theory/electroMagnetism/solenoidMagneticFieldProp.dart';
export './theory/electroMagnetism/fluxAndAreaIntegral.dart';
export './theory/electroMagnetism/magneticGaussLaw.dart';
export './theory/electroMagnetism/electromagneticInductionLaw.dart';
export './theory/electroMagnetism/ampereMaxwellLaw.dart';
export './theory/electroMagnetism/permittivity.dart';
export './theory/electroMagnetism/permeability.dart';
export './theory/electroMagnetism/permittivityAndPermeabilityTable.dart';
export './theory/electroMagnetism/ampereMaxwellLawInMatter.dart';
export './theory/electroMagnetism/electoricGaussLawInMatter.dart';
export './theory/electroMagnetism/definitionOfElectricField.dart';
export './theory/electroMagnetism/definitionOfMagneticField.dart';
export './theory/electroMagnetism/electromagneticForce.dart';
export './theory/electroMagnetism/rightHandRule.dart';
export './theory/electroMagnetism/definitionOfElectricChargeAndCurrent.dart';
export './theory/electroMagnetism/magneticDipole.dart';
export './theory/electroMagnetism/electricDipole.dart';
export './theory/electroMagnetism/dipoleComparison.dart';
export './theory/electroMagnetism/rcCircuit.dart';
export './theory/electroMagnetism/rcCircuitDischarge.dart';
export './theory/electroMagnetism/bioSarvartLawForCircleCurrent.dart';
export './theory/electroMagnetism/bioSarvartLaw.dart';
export './theory/electroMagnetism/e_field_spherical_charge_distribution.dart';
export './theory/electroMagnetism/e_field_infinite_uniform_sheet.dart';
export './theory/electroMagnetism/magnetic_field_circular_loop_on_axis_z0.dart';
export './theory/electroMagnetism/magnetic_field_circular_loop_on_axis.dart';
export './theory/electroMagnetism/magnetic_field_circular_loop_general_point.dart';
export './theory/electroMagnetism/circular_loop_magnetic_field_satisfies_ampere_law.dart';
export './theory/electroMagnetism/magnetic_field_solenoid_by_summation_of_circular_loop.dart';
export './theory/electroMagnetism/solenoid_self_inductance.dart';
export './theory/electroMagnetism/rl_circuit.dart';
export './theory/electroMagnetism/lc_circuit.dart';
export './theory/electroMagnetism/rlc_circuit.dart';
export './theory/electroMagnetism/e_field_point_charge.dart';
export './theory/electroMagnetism/coulombs_law.dart';

/* ---------- Common / Mappings (力学 ⇄ 電磁気 の対応表) ---------- */
export './theory/electroMagnetism/mech_em_differential_equations_mapping.dart';
export './theory/electroMagnetism/mechanics_em_electricfield_gravity_mapping.dart';